locataire_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:index }

locataire_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:edit }
