admin_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:index }

admin_create_syndic:
    path:     /create/syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:createSyndic }

admin_list_syndics:
    path:     /list/syndics
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:listSyndic }

admin_show_syndic:
    path:     /show/syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:showSyndic }

admin_edit_syndic:
    path:     /edit/syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:editSyndic }

admin_delete_syndic:
    path:     /delete/syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:deleteSyndic }

# ROUTE LIEES AUX MESSAGES
#--------------------------

admin_show_message:
    path: /inbox/message/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:showMessage}

admin_show_message_from_corbeille:
    path: /corbeille/message/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:showMessageFromCorbeille}

admin_show_message_from_envoye:
    path: /messagesEnvoyes/message/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:showMessagefromEnvoyes}

admin_inbox:
    path: /inbox
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:inbox}

admin_delete_message:
    path: /delete/message/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:deleteMessage}

admin_messages_envoyes:
    path: /messagesEnvoyes
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:messagesEnvoyes}

admin_corbeille:
    path: /corbeille
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:corbeille}

admin_delete_message_corbeille:
    path: /corbeille/message/{id}/delete
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:deleteMessageCorbeille}

admin_nowSupprime:
    path: /inbox/message/{id}/delete
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:nowSupprime}

admin_notLu:
    path: /inbox/message/{id}/unread
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:notLu}

admin_revertMessage:
    path: /inbox/message/{id}/revert
    defaults: {  _controller: AKYOSEasyCoproBundle:Admin:revertMessage}
