akyos_easy_copro_homepage:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Connexion:index }

akyos_easy_copro_contact:
    path:     /send
    defaults: { _controller: AKYOSEasyCoproBundle:Contact:contact }

akyos_easy_copro_mentions:
    path:     /mentions
    defaults: { _controller: AKYOSEasyCoproBundle:Default:mentions }

akyos_easy_copro_backend_syndic_index:
    path:     /syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:index }

akyos_easy_copro_backend_copro_index:
    path:     /copro
    defaults: { _controller: AKYOSEasyCoproBundle:Copro:index }

akyos_easy_copro_backend_locataire_index:
    path:     /locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:index }

akyos_easy_copro_backend_artisan_index:
    path:     /artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:index }

akyos_easy_copro_backend_admin_index:
    path:     /admin
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:index }

akyos_easy_copro_backend_admin_create_syndic:
    path:     /admin/create_syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:createSyndic }

akyos_easy_copro_backend_admin_list_syndic:
    path:     /admin/list_syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:listSyndic }

akyos_easy_copro_backend_admin_show_syndic:
    path:     /admin/show_syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:showSyndic }

akyos_easy_copro_backend_admin_edit_syndic:
    path:     /admin/edit_syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:editSyndic }

akyos_easy_copro_backend_admin_delete_syndic:
    path:     /admin/delete_syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:deleteSyndic }