locataire_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:index }

locataire_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:edit }

locataire_show:
    path:     /show
    defaults: {_controller: AKYOSEasyCoproBundle:Locataire:show }

locataire_parameters:
    path: /parameters
    defaults: {_controller: AKYOSEasyCoproBundle:Locataire:parameters }

locataire_show_copropriete:
    path: /show/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:showCopropriete}

locataire_edit_copropriete:
    path: /edit/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:editCopropriete}

# ROUTE LIEES AUX DOCUMENTS
#--------------------------

locataire_gestion_documents:
    path: /list/docs
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:gestionDocuments }

locataire_show_document:
    path: /show/doc/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:showDocument}

locataire_list_categorie_documents:
    path: /list/docs/{categorieId}
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:listCategorieDocuments }

# ROUTE LIEES AUX MESSAGES
#--------------------------

locataire_show_message:
        path: /inbox/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:showMessage}

locataire_show_message_from_corbeille:
        path: /corbeille/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:showMessageFromCorbeille}

locataire_show_message_from_envoye:
        path: /messagesEnvoyes/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:showMessagefromEnvoyes}

locataire_inbox:
        path: /inbox
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:inbox}

locataire_delete_message:
        path: /delete/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:deleteMessage}

locataire_messages_envoyes:
        path: /messagesEnvoyes
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:messagesEnvoyes}

locataire_corbeille:
        path: /corbeille
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:corbeille}

locataire_delete_message_corbeille:
        path: /corbeille/message/{id}/delete
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:deleteMessageCorbeille}

locataire_nowSupprime:
        path: /inbox/message/{id}/delete
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:nowSupprime}

locataire_notLu:
        path: /inbox/message/{id}/unread
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:notLu}

locataire_revertMessage:
        path: /inbox/message/{id}/revert
        defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:revertMessage}
