artisan_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:index }

artisan_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:edit }

artisan_show:
    path:     /show
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:show }

# ROUTE LIEES AUX DOCUMENTS
#--------------------------

artisan_gestion_documents:
    path: /list/docs
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:gestionDocuments }

artisan_show_document:
    path: /show/doc/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:showDocument}

# ROUTE LIEES AUX MESSAGES
#--------------------------

artisan_show_message:
        path: /inbox/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:showMessage}

artisan_show_message_from_corbeille:
        path: /corbeille/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:showMessageFromCorbeille}

artisan_show_message_from_envoye:
        path: /messagesEnvoyes/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:showMessagefromEnvoyes}

artisan_inbox:
        path: /inbox
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:inbox}

artisan_delete_message:
        path: /delete/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:deleteMessage}

artisan_messages_envoyes:
        path: /messagesEnvoyes
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:messagesEnvoyes}

artisan_corbeille:
        path: /corbeille
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:corbeille}

artisan_delete_message_corbeille:
        path: /corbeille/message/{id}/delete
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:deleteMessageCorbeille}

artisan_nowSupprime:
        path: /inbox/message/{id}/delete
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:nowSupprime}

artisan_notLu:
        path: /inbox/message/{id}/unread
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:notLu}

artisan_revertMessage:
        path: /inbox/message/{id}/revert
        defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:revertMessage}
