akyos_easy_copro_homepage:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Connexion:index }

akyos_easy_copro_contact:
    path:     /contact
    defaults: { _controller: AKYOSEasyCoproBundle:Contact:contact }

akyos_easy_copro_mentions:
    path:     /mentions
    defaults: { _controller: AKYOSEasyCoproBundle:Default:mentions }

akyos_easy_copro_backend_syndic_index:
    path:     /syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:index }

akyos_easy_copro_backend_copro_index:
    path:     /copro
    defaults: { _controller: AKYOSEasyCoproBundle:Copro:index }

akyos_easy_copro_backend_locataire_index:
    path:     /locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:index }

akyos_easy_copro_backend_artisan_index:
    path:     /artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:index }

akyos_easy_copro_backend_admin_index:
    path:     /admin
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:index }

akyos_easy_copro_backend_admin_create_syndic:
    path:     /admin/create_syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:createSyndic }

akyos_easy_copro_backend_admin_list_syndic:
    path:     /admin/list_syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:listSyndic }

akyos_easy_copro_backend_admin_show_syndic:
    path:     /admin/show_syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:showSyndic }

akyos_easy_copro_backend_admin_edit_syndic:
    path:     /admin/edit_syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:editSyndic }

akyos_easy_copro_backend_admin_delete_syndic:
    path:     /admin/delete_syndic/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:deleteSyndic }

akyos_easy_copro_backend_syndic_addArtisan:
    path:     /syndic/add/Artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:register }

akyos_easy_copro_backend_syndic_addCopro:
    path:     /syndic/add/Copro
    defaults: { _controller: AKYOSEasyCoproBundle:Copro:register }

akyos_easy_copro_backend_syndic_addLocataire:
    path:     /syndic/add/Locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:register}

akyos_easy_copro_backend_locataire_listLocataire:
    path:     /locataire/list/Locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:listLocataire}

akyos_easy_copro_backend_artisan_listArtisan:
    path:     /locataire/list/Artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:listArtisan}

akyos_easy_copro_backend_copro_listCopro:
    path:     /locataire/list/Copro
    defaults: { _controller: AKYOSEasyCoproBundle:Copro:listCopro}

akyos_easy_copro_backend_locataire_showLocataire:
    path:     /locataire/show/Locataire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:showLocataire }

akyos_easy_copro_backend_artisan_showArtisan:
    path:     /artisan/show/Artisan/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:showArtisan }

akyos_easy_copro_backend_copro_showCopro:
    path:     /copro/show/Copro/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Copro:showCopro }

akyos_easy_copro_backend_syndic_editLocataire:
    path:     /syndic/edit/Locataire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editLocataire }

akyos_easy_copro_backend_syndic_editArtisan:
    path:     /syndic/edit/Artisan/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editArtisan }

akyos_easy_copro_backend_syndic_editCopro:
    path:     /syndic/edit/Copro/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editCopro }

akyos_easy_copro_backend_syndic_deleteLocataire:
    path:     /syndic/delete/Locataire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteLocataire }

akyos_easy_copro_backend_syndic_deleteArtisan:
    path:     /syndic/delete/Artisan/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteArtisan }

akyos_easy_copro_backend_syndic_deleteCopro:
    path:     /syndic/delete/Copro/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteCopro }

