akyos_easy_copro_homepage:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Connexion:index }

akyos_easy_copro_contact:
    path:     /contact
    defaults: { _controller: AKYOSEasyCoproBundle:Contact:contact }

akyos_easy_copro_mentions:
    path:     /mentions
    defaults: { _controller: AKYOSEasyCoproBundle:Default:mentions }

akyos_easy_copro_backend_syndic_index:
    path:     /syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:index }

akyos_easy_copro_backend_copro_index:
    path:     /copro
    defaults: { _controller: AKYOSEasyCoproBundle:Copro:index }

akyos_easy_copro_backend_locataire_index:
    path:     /locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:index }

akyos_easy_copro_backend_artisan_index:
    path:     /artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:index }

akyos_easy_copro_backend_admin_index:
    path:     /admin
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:index }

akyos_easy_copro_backend_syndic_newArtisan:
    path:     /syndic/newArtisan
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:newArtisan }

akyos_easy_copro_backend_syndic_newCopro:
    path:     /syndic/newCopro
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:newCopro }

akyos_easy_copro_backend_syndic_newLocataire:
    path:     /syndic/newLocataire
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:newLocataire }
