akyos_easy_copro_homepage:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Connexion:index }

akyos_easy_copro_contact:
    path:     /contact
    defaults: { _controller: AKYOSEasyCoproBundle:Contact:contact }

akyos_easy_copro_mentions:
    path:     /mentions
    defaults: { _controller: AKYOSEasyCoproBundle:Default:mentions }

akyos_easy_copro_backend_syndic_index:
    path:     /syndic
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:index }

akyos_easy_copro_backend_copro_index:
    path:     /copro
    defaults: { _controller: AKYOSEasyCoproBundle:Copro:index }

akyos_easy_copro_backend_locataire_index:
    path:     /locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:index }

akyos_easy_copro_backend_artisan_index:
    path:     /artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:index }

akyos_easy_copro_backend_admin_index:
    path:     /admin
    defaults: { _controller: AKYOSEasyCoproBundle:Admin:index }

akyos_easy_copro_backend_syndic_addArtisan:
    path:     /syndic/add/Artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:addArtisan }

akyos_easy_copro_backend_syndic_addCopro:
    path:     /syndic/add/Copro
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:addCopro }

akyos_easy_copro_backend_syndic_addLocataire:
    path:     /syndic/add/Locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:addLocataire }

akyos_easy_copro_backend_syndic_editArtisan:
    path:     /syndic/edit/Artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editArtisan }

akyos_easy_copro_backend_syndic_editCopro:
    path:     /syndic/edit/Copro
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editCopro }

akyos_easy_copro_backend_syndic_editLocataire:
    path:     /syndic/edit/Locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editLocataire }
