akyos_easy_copro_homepage:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Default:index }

akyos_easy_copro_contact:
    path:     /send
    defaults: { _controller: AKYOSEasyCoproBundle:Contact:contact }

akyos_easy_copro_mentions:
    path:     /mentions
    defaults: { _controller: AKYOSEasyCoproBundle:Default:mentions }