homepage:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:FrontOffice:index }

contact:
    path:     /contact
    defaults: { _controller: AKYOSEasyCoproBundle:FrontOffice:contact }

mentions:
    path:     /mentions
    defaults: { _controller: AKYOSEasyCoproBundle:FrontOffice:mentions }

acme_demo_pdf:
    path: /pdf
    defaults: { _controller: AKYOSEasyCoproBundle:FrontOffice:pdf }
