coproprietaire_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:index }

coproprietaire_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:edit }

coproprietaire_show:
    path:     /show/{id}
    defaults: {_controller: AKYOSEasyCoproBundle:Coproprietaire:show }