coproprietaire_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:index }

coproprietaire_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:edit }

coproprietaire_show:
    path:     /show
    defaults: {_controller: AKYOSEasyCoproBundle:Coproprietaire:show }

coproprietaire_show_document:
    path: /show/doc/{id}/
    defaults: {  _controller: AKYOSEasyCoproBundle:Coproprietaire:showDocument}

coproprietaire_gestion_documents:
    path: /documents
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:gestionDocuments }