akyos_easy_copro_homepage:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Default:index }

SubmitForm:
    path:     /send
    defaults: { _controller: AKYOSEasyCoproBundle:Default:SubmitForm }

mentions:
    path:     /mentions
    defaults: { _controller: AKYOSEasyCoproBundle:Default:mentions }