# ROUTE LIEES AU COMPTE SYNDIC ACTUEL
#------------------------------------

syndic_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:index }

syndic_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:edit }

syndic_show:
    path:     /show
    defaults: {_controller: AKYOSEasyCoproBundle:Syndic:show }


# ROUTE LIEES AUX COPROPRIETAIRES
#--------------------------------

syndic_create_coproprietaire:
    path:     /create/coproprietaire
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:createCoproprietaire }

syndic_edit_coproprietaire:
    path:     /edit/coproprietaire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editCoproprietaire }

syndic_show_coproprietaire:
    path:     /show/coproprietaire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:showCoproprietaire }

syndic_list_coproprietaires:
    path:     /list/coproprietaires
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:listCoproprietaires }

syndic_delete_coproprietaire:
    path:     /delete/coproprietaire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteCoproprietaire }


# ROUTE LIEES AUX LOCATAIRES
#---------------------------

syndic_create_locataire:
    path:     /create/locataire
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:createLocataire }

syndic_edit_locataire:
    path:     /edit/locataire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editLocataire }

syndic_show_locataire:
    path:     /show/locataire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:showLocataire }

syndic_list_locataires:
    path:     /list/locataires
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:listLocataires }

syndic_delete_locataire:
    path:     /delete/locataire/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteLocataire }

# ROUTE LIEES AUX ARTISANS
#-------------------------

syndic_gestion_artisans:
    path:     /list/artisans
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:gestionArtisans }

syndic_create_artisan:
    path:     /create/artisan
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:createArtisan }

syndic_edit_artisan:
    path:     /edit/artisan/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editArtisan }

syndic_show_artisan:
    path:     /show/artisan/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:showArtisan }

syndic_delete_artisan:
    path:     /delete/artisan/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteArtisan }


# ROUTE LIEES AUX COPROPRIETES
#-----------------------------

syndic_create_copropriete:
    path:     /create/copropriete
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:createCopropriete }

syndic_edit_copropriete:
    path:     /edit/copropriete/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editCopropriete }

syndic_show_copropriete:
    path:     /show/copropriete/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:showCopropriete }


syndic_list_coproprietes:
    path:     /list/coproprietes
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:listCoproprietes }

syndic_delete_copropriete:
    path:     /delete/copropriete/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteCopropriete }


# ROUTE LIEES AUX LOTS
#---------------------

syndic_create_lot:
    path:     /create/lot
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:createLot }

syndic_edit_lot:
    path:     /edit/lot/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:editLot }

syndic_show_lot:
    path:     /show/lot/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:showLot }

syndic_list_lots:
    path:     /list/lots
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:listLots }

syndic_delete_lot:
    path:     /delete/lot/{id}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:deleteLot }


# ROUTE LIEES AUX DOCUMENTS
#--------------------------

syndic_gestion_documents:
    path: /list/docs
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:gestionDocuments }

syndic_create_document:
    path: /create/doc
    defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:createDocument}

syndic_edit_document:
    path: /edit/doc/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:editDocument}

syndic_show_document:
    path: /show/doc/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:showDocument}

syndic_delete_document:
    path: /delete/doc/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:deleteDocument}

syndic_list_categorie_documents:
    path: /list/docs/{categorieId}
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:listCategorieDocuments }


# ROUTE LIEES AUX CATEGORIES
#--------------------------

syndic_gestion_categories:
    path: /list/categories
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:gestionCategories }

syndic_create_categorie:
    path: /create/categorie
    defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:createCategorie }

syndic_edit_categorie:
    path: /edit/categorie/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:editCategorie }

syndic_delete_categorie:
    path: /delete/categorie/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:deleteCategorie }


# ROUTE LIEES AUX MESSAGES
#--------------------------

syndic_gestion_messages:
    path: /list/messages
    defaults: { _controller: AKYOSEasyCoproBundle:Syndic:gestionMessages }

syndic_send_message:
        path: /send/message
        defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:sendMessage}

syndic_show_message:
        path: /show/message/{id}/
        defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:showMessage}

syndic_delete_message:
        path: /delete/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:deleteMessage}

syndic_inbox:
        path: /inbox
        defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:inbox}

syndic_messages_envoyes:
        path: /messagesEnvoyes
        defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:messagesEnvoyes}

syndic_corbeille:
        path: /corbeille
        defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:corbeille}

syndic_delete_message_corbeille:
        path: /corbeille/message/{id}
        defaults: {  _controller: AKYOSEasyCoproBundle:Syndic:deleteMessageCorbeille}

