services:
    akyos.password_resetting:
        class: AKYOS\EasyCoproBundle\EventListener\PasswordResettingListener
        arguments: ['@router', '@session']
        tags:
            - { name: kernel.event_subscriber }
    akyos.confirm_registration:
        class: AKYOS\EasyCoproBundle\Service\RegistrationConfirmation
        arguments: ['@fos_user.mailer','@fos_user.util.token_generator','@router','@session', '@service_container']

    akyos.generate_document:
        class: AKYOS\EasyCoproBundle\Service\GenerateDocument
        arguments: ['@service_container']

    form.type.create_document:
        class: AKYOS\EasyCoproBundle\Form\CreateDocumentType
        arguments: ['@service_container', '@session']
        tags:
            - { name: form.type }

    form.type.edit_document:
        class: AKYOS\EasyCoproBundle\Form\EditDocumentType
        arguments: ['@service_container', '@session']
        tags:
            - { name: form.type }

    app.twig_extension:
        class: AKYOS\EasyCoproBundle\Service\ActuelCoproprietaireFilter
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    twig.format.telnumber:
        class: AKYOS\EasyCoproBundle\Service\TelNumberTwigFilter
        tags:
            - { name: twig.extension }

    twig.format.compterebours:
        class: AKYOS\EasyCoproBundle\Service\CompteReboursTwigFilter
        tags:
            - { name: twig.extension }

    app.form.registration:
        class: AKYOS\EasyCoproBundle\Form\CreateUserType
        tags:
            - { name: form.type, alias: app_user_registration }

    form.type.create_coproprietaire:
        class: AKYOS\EasyCoproBundle\Form\CreateCoproprietaireType
        arguments: ['@service_container']
        tags:
            - { name: form.type }

    form.type.edit_coproprietaire:
            class: AKYOS\EasyCoproBundle\Form\EditCoproprietaireType
            arguments: ['@service_container']
            tags:
                - { name: form.type }