services:
    akyos.password_resetting:
        class: AKYOS\EasyCoproBundle\EventListener\PasswordResettingListener
        arguments: ['@router', '@session']
        tags:
            - { name: kernel.event_subscriber }

    akyos.confirm_registration:
        class: AKYOS\EasyCoproBundle\Service\RegistrationConfirmation
        arguments: ['@fos_user.mailer','@fos_user.util.token_generator','@router','@session', '@service_container']

    akyos.generate_document:
        class: AKYOS\EasyCoproBundle\Service\GenerateDocument
        arguments: ['@service_container']

    form.type.create_document:
        class: AKYOS\EasyCoproBundle\Form\CreateDocumentType
        arguments: ['@service_container', '@session']
        tags:
            - { name: form.type }

    form.type.edit_document:
        class: AKYOS\EasyCoproBundle\Form\EditDocumentType
        arguments: ['@service_container', '@session']
        tags:
            - { name: form.type }

    akyos.twig.filters:
        class: AKYOS\EasyCoproBundle\Service\TwigFilters
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    app.form.registration:
        class: AKYOS\EasyCoproBundle\Form\CreateUserType
        tags:
            - { name: form.type, alias: app_user_registration }

    form.type.create_coproprietaire:
        class: AKYOS\EasyCoproBundle\Form\CreateCoproprietaireType
        arguments: ['@service_container']
        tags:
            - { name: form.type }

    form.type.edit_coproprietaire:
        class: AKYOS\EasyCoproBundle\Form\EditCoproprietaireType
        arguments: ['@service_container']
        tags:
            - { name: form.type }

    form.type.create_locataire:
        class: AKYOS\EasyCoproBundle\Form\CreateLocataireType
        arguments: ['@service_container']
        tags:
            - { name: form.type }

    form.type.edit_locataire:
        class: AKYOS\EasyCoproBundle\Form\EditLocataireType
        arguments: ['@service_container']
        tags:
            - { name: form.type }

    form.type.edit_artisan:
            class: AKYOS\EasyCoproBundle\Form\EditArtisanType
            arguments: ['@service_container']
            tags:
                - { name: form.type }