services:
    akyos.password_resetting:
        class: AKYOS\EasyCoproBundle\EventListener\PasswordResettingListener
        arguments: ['@router', '@session']
        tags:
            - { name: kernel.event_subscriber }
