imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    img_documents: '%kernel.root_dir%/web/assets/img/docs'
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    AKYOSBackofficeBundle: ~
                    AKYOSUserBundle: ~
                    AKYOSMailboxBundle: ~
                    AKYOSPostitBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AKYOS\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: EasyCopro
    registration:
        form:
            type: AKYOS\UserBundle\Form\CreateUserType
        confirmation:
            enabled: true
            template: 'FOSUserBundle:Registration:email.txt.twig'
    resetting:
        email:
            template: 'FOSUserBundle:Resetting:email.txt.twig'

vich_uploader:
    db_driver: orm
    mappings:
        documents:
            uri_prefix:         /uploads/document
            upload_destination: '%kernel.root_dir%/../web/uploads/document'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
        avatar_images:
            uri_prefix:         /uploads/avatar
            upload_destination: '%kernel.root_dir%/../web/uploads/avatar'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   false
        copropriete_images:
            uri_prefix:         /uploads/copropriete
            upload_destination: '%kernel.root_dir%/../web/uploads/copropriete'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   false

# KNP Snappy Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
