akyos_frontoffice:
    resource: "@AKYOSFrontofficeBundle/Resources/config/routing.yml"
    prefix:   /

akyos_easy_copro_postit:
    resource: "@AKYOSEasyCoproBundle/Resources/config/routing.yml"
    prefix:   /

akyos_easy_copro_back_office_admin:
    resource: "@AKYOSEasyCoproBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

akyos_easy_copro_back_office_syndic:
    resource: "@AKYOSEasyCoproBundle/Resources/config/routing_syndic.yml"
    prefix:   /syndic

akyos_easy_copro_back_office_coproprietaire:
    resource: "@AKYOSEasyCoproBundle/Resources/config/routing_coproprietaire.yml"
    prefix:   /coproprietaire

akyos_easy_copro_back_office_locataire:
    resource: "@AKYOSEasyCoproBundle/Resources/config/routing_locataire.yml"
    prefix:   /locataire

akyos_easy_copro_back_office_artisan:
    resource: "@AKYOSEasyCoproBundle/Resources/config/routing_artisan.yml"
    prefix:   /artisan

akyos_easy_copro_mailbox:
    resource: "@AKYOSMailboxBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"