akyos_frontoffice:
    resource: "@AKYOSFrontofficeBundle/Resources/config/routing.yml"
    prefix:   /

akyos_user:
    resource: "@AKYOSUserBundle/Resources/config/routing.yml"
    prefix:   /user

akyos_backoffice:
    resource: "@AKYOSEasyCoproBundle/Resources/config/routing.yml"
    prefix:   /

akyos_mailbox:
    resource: "@AKYOSMailboxBundle/Resources/config/routing.yml"
    prefix:   /

akyos_postit:
    resource: "@AKYOSPostitBundle/Resources/config/routing.yml"
    prefix:   /postit

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"