postit_index:
    path:     /
    defaults: { _controller: "AKYOSEasyCoproBundle:Postit:index" }
    methods:  GET

postit_show:
    path:     /{id}/show
    defaults: { _controller: "AKYOSEasyCoproBundle:Postit:show" }
    methods:  GET

postit_new:
    path:     /new
    defaults: { _controller: "AKYOSEasyCoproBundle:Postit:new" }
    methods:  [GET, POST]

postit_edit:
    path:     /{id}/edit
    defaults: { _controller: "AKYOSEasyCoproBundle:Postit:edit" }
    methods:  [GET, POST]

postit_delete:
    path:     /{id}/delete
    defaults: { _controller: "AKYOSEasyCoproBundle:Postit:delete" }
