coproprietaire_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:index }

coproprietaire_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:edit }

coproprietaire_show:
    path:     /show
    defaults: {_controller: AKYOSEasyCoproBundle:Coproprietaire:show }

coproprietaire_parameters:
    path: /parameters
    defaults: {_controller: AKYOSEasyCoproBundle:Coproprietaire:parameters }

coproprietaire_show_document:
    path: /show/doc/{id}/
    defaults: {  _controller: AKYOSEasyCoproBundle:Coproprietaire:showDocument}

coproprietaire_gestion_documents:
    path: /documents
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:gestionDocuments }

coproprietaire_list_categorie_documents:
    path: /list/docs/{categorieId}
    defaults: { _controller: AKYOSEasyCoproBundle:Coproprietaire:listCategorieDocuments }

coproprietaire_show_copropriete:
    path: /show/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Coproprietaire:showCopropriete}

coproprietaire_edit_copropriete:
    path: /edit/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Coproprietaire:editCopropriete}

coproprietaire_show_syndic:
    path: /show/syndic/
    defaults: {  _controller: AKYOSEasyCoproBundle:Coproprietaire:showSyndic}

coproprietaire_edit_syndic:
    path: /edit/syndic/
    defaults: {  _controller: AKYOSEasyCoproBundle:Coproprietaire:editSyndic}
