artisan_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:index }

artisan_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:edit }

artisan_show:
    path:     /show
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:show }

artisan_parameters:
    path: /parameters
    defaults: {_controller: AKYOSEasyCoproBundle:Artisan:parameters }
    
artisan_show_copropriete:
    path: /show/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:showCopropriete}

artisan_edit_copropriete:
    path: /edit/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:editCopropriete}
    
    
# ROUTE LIEES AUX DOCUMENTS
#--------------------------

artisan_gestion_documents:
    path: /list/docs
    defaults: { _controller: AKYOSEasyCoproBundle:Artisan:gestionDocuments }

artisan_show_document:
    path: /show/doc/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Artisan:showDocument}
