locataire_index:
    path:     /
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:index }

locataire_edit:
    path:     /edit
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:edit }

locataire_show:
    path:     /show
    defaults: {_controller: AKYOSEasyCoproBundle:Locataire:show }

locataire_parameters:
    path: /parameters
    defaults: {_controller: AKYOSEasyCoproBundle:Locataire:parameters }

locataire_show_copropriete:
    path: /show/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:showCopropriete}

locataire_edit_copropriete:
    path: /edit/copropriete
    defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:editCopropriete}

# ROUTE LIEES AUX DOCUMENTS
#--------------------------

locataire_gestion_documents:
    path: /list/docs
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:gestionDocuments }

locataire_show_document:
    path: /show/doc/{id}
    defaults: {  _controller: AKYOSEasyCoproBundle:Locataire:showDocument}

locataire_list_categorie_documents:
    path: /list/docs/{categorieId}
    defaults: { _controller: AKYOSEasyCoproBundle:Locataire:listCategorieDocuments }
