akyos_easy_copro_back_office_admin:
    resource: "routing/routing_admin.yml"
    prefix:   /admin

akyos_easy_copro_back_office_syndic:
    resource: "routing/routing_syndic.yml"
    prefix:   /syndic

akyos_easy_copro_back_office_coproprietaire:
    resource: "routing/routing_coproprietaire.yml"
    prefix:   /coproprietaire

akyos_easy_copro_back_office_locataire:
    resource: "routing/routing_locataire.yml"
    prefix:   /locataire

akyos_easy_copro_back_office_artisan:
    resource: "routing/routing_artisan.yml"
    prefix:   /artisan