services:
    form.document:
        class: AKYOS\DocumentBundle\Form\DocumentType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    twig.filters.document:
        class: AKYOS\DocumentBundle\Service\TwigFilters
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }
