AKYOS\DocumentBundle\Entity\Category:
    properties:
        nom:
            - NotBlank: ~
            - Length:
                max: 5
                maxMessage: 'Le nom ne doit pas dépasser {{ limit }} caractères'
        couleur:
            - NotNull: ~
            - Regex:
                pattern: '/^#[0-9a-fA-F]{6}$/'
                message: 'La couleur doit être au format hexadécimal'

AKYOSDocumentBundle\Entity\Document:
    properties:
        titre:
            - NotBlank: ~
            - Length:
                max: 255
                maxMessage: 'Le titre ne doit pas dépasser {{ limit }} caractères'
        file:
            - NotNull: ~
        category:
            - NotNull: ~
        copropriete:
            - NotNull: ~

